- name: Install docker packages && git & openssl
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
   - apt-transport-https
   - ca-certificates
   - curl
   - software-properties-common
   - libssl-dev
   - git
   - python3-pip

- name: Add Docker s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Verify that we have the key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present    

- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes    
    
- name: Update apt packages
  apt:
    update_cache: yes

- name: Install docker
  apt:
    name: docker-ce 
    state: present
    update_cache: yes

- name: Create "docker" group
  group:
     name: "docker"
     state: present

- name: Add remote "ubuntu" user to "docker" group
  user:
   name: "ubuntu"
   group: "docker"
   append: yes

- name: Install docker-compose
  apt:
    name: docker-compose=1.8.*
    state: present
    update_cache: yes

- name: pip install docker and docker-compose module
  pip:
    name:
      - docker
      - docker-compose
    state: present
